### PR TITLE
Update rasterio

### PR DESCRIPTION
**Pull request by klinkow**
Updates dependency Rasterio from version `>=1.0a12` to `^1.4.3`. Updates project to use Poetry, replacing `Pipfile` with `pyproject.toml`.

### CODE REVIEW

File: trefoil/netcdf/tests/test_crs.py [hunk 1]
```diff
@@ -34,7 +34,6 @@ def test_get_crs(tmpdir):
 
     out_data = CRS.from_string(out_proj4).to_dict()
 
-    assert len(out_data) == 8  # There should be 8 parameters
```
Comment (klinkow) [inline trefoil/netcdf/tests/test_crs.py:37]: This assertion failed (6 != 8), but it's hard to know what 8 things were wanted. More direct assertions of the contents of `out_data` follow.

File: trefoil/netcdf/tests/test_crs.py [hunk 2]
```diff
@@ -56,7 +55,6 @@ def test_get_crs(tmpdir):
 
     out_data = CRS.from_string(out_proj4).to_dict()
 
-    assert len(out_data) == 4  # There should be 4 parameters
```
Comment (klinkow) [inline trefoil/netcdf/tests/test_crs.py:59]: This assertion failed, but it's hard to know what 4 things were wanted. More direct assertions of the contents of `out_data` follow.

File: trefoil/render/renderers/tests/test_renderers.py [hunk 3]
```diff
@@ -20,7 +20,6 @@ def test_stretched_renderer(tmpdir):
     assert renderer.name == 'stretched'
 
     img = renderer.render_image(data)
-    assert len(img.getpalette()) / 3 == 256
```
Comment (klinkow) [inline trefoil/render/renderers/tests/test_renderers.py:23]: This assertion was failing, but I thought it wasn't needed if all of the subsequent assertions were passing.

Comment (nikmolnar) [reply trefoil/render/renderers/tests/test_renderers.py:23]: How was it failing? The value didn't equal 256? Or it was causing an exception?

File: pyproject.toml [hunk 4]
```diff
@@ -0,0 +1,31 @@
+[tool.poetry]
+name = "trefoil"
+version = "0.1.0"
+description = "Geospatial operations with NetCDF files and numpy arrays."
+authors = ["Conservation Biology Institute"]
+readme = "README.md"
+
+[tool.poetry.dependencies]
```
Comment (nikmolnar) [inline pyproject.toml:8]: We need to add `six` to the dependencies. I tried importing a trefoil module and got an error about no module `six`.

Comment (klinkow) [reply pyproject.toml:8]: Added

File: trefoil/netcdf/tests/test_crs.py (hunk 1 above)
Comment (nikmolnar) [reply trefoil/netcdf/tests/test_crs.py:37]: Weird, when I run this code in the interpreter, I get a dict with 10 items 🤔 Anyway, I think it's okay to remove this assertion, since in the next one, we're verifying the CRS from the dataset is what we expect.

Comment (klinkow) [reply trefoil/netcdf/tests/test_crs.py:37]: Sorry, 10 is right. I remembered a difference of 2 when writing the comment and went the wrong direction.

File: trefoil/render/renderers/tests/test_renderers.py (hunk 3 above)
Comment (klinkow) [reply trefoil/render/renderers/tests/test_renderers.py:23]: Thanks for the suggestion. The images look identical.

**Comment by nikmolnar** [comment]
Have you tested this out with runs in SST? I'm getting blank result, and the raster produced seems to be all one value (128; probably the mask value since it shows completely invisible in the tool).

File: pyproject.toml [hunk 5]
```diff
@@ -0,0 +1,32 @@
+[tool.poetry]
+name = "trefoil"
+version = "0.1.0"
```
Comment (nikmolnar) [inline pyproject.toml:3]: This should be `0.4.0`.

**Comment by klinkow** [comment]
> I'm getting blank result, and the raster produced seems to be all one value (128; probably the mask value since it shows completely invisible in the tool).

I'm not having any issues, but maybe I've left out a step in my testing. FYI since yesterday I've made the version update you suggested in this branch and also updated the ncdjango `test-trefoil-update` branch to target this branch instead of `main` (to make this testing easier). Here's my testing steps:

I added these changes to seedlot-selection-tool's `develop` branch (as of 7:50AM Pacific 6/24):
 
image

I ran `poetry lock`, `poetry install` from seedlot-selection-tool, then `docker compose up`.

I ran the following configuration:

image
(also works adding a geographic constraint, but the results were small for a screenshot)

 Toggling on MAT layer:
image

**Comment by klinkow** [comment]
Yep, I'm seeing the same errors I think. The task succeeds, but it can't serve the output NetCDF file as tiles. I get an error loading that file into QGIS.

Hmm... I'm thinking about how I can make a test that's better than logging out results along the way and comparing with working results. Maybe I'll start there and see where it takes me.

**Comment by nikmolnar** [comment]
> Yep, I'm seeing the same errors I think. The task succeeds, but it can't serve the output NetCDF file as tiles. I get an error loading that file into QGIS.
> 
> Hmm... I'm thinking about how I can make a test that's better than logging out results along the way and comparing with working results. Maybe I'll start there and see where it takes me.

Sounds like a plan 👍

File: pyproject.toml [hunk 6]
```diff
@@ -0,0 +1,32 @@
+[tool.poetry]
+name = "trefoil"
+version = "0.4.0"
+description = "Geospatial operations with NetCDF files and numpy arrays."
+authors = ["Conservation Biology Institute"]
+readme = "README.md"
+
+[tool.poetry.dependencies]
+python = ">=3.10,<3.11"
```
Comment (nikmolnar) [inline pyproject.toml:9]: Will this library really not work with Python 3.11+? It looks like rasterio supports 3.9+.

**Review by nikmolnar — CHANGES_REQUESTED** [review]

File: pyproject.toml (hunk 6 above)
Comment (klinkow) [reply pyproject.toml]: Nice catch. I updated this to `python = ">=3.9,<3.12"` after testing:
3.9 ✅  
3.10 ✅  
3.11 ✅ 
3.12 ❌ 
3.13 ❌

File: trefoil/render/renderers/stretched.py [hunk 7]
```diff
@@ -112,7 +112,7 @@ def render_image(self, data, row_major_order=True):
         values = self._mask_fill_value(data.ravel())
 
         # derive palette index, and clip to [0, num_colors - 1]
-        stretched = ((values - self.min_value) * factor).astype(numpy.int)
+        stretched = ((values - self.min_value) * factor).astype(numpy.int_)
```
[the remark this answers is not in the document]
Comment (klinkow) [reply trefoil/render/renderers/stretched.py]: When running tests using `numpy.int`, I get:
```
FAILED trefoil/render/renderers/tests/test_renderers.py::test_stretched_renderer - AttributeError: module 'numpy' has no attribute 'int'.
```
According to [this SO thread](https://stackoverflow.com/questions/74946845/attributeerror-module-numpy-has-no-attribute-int): 

> numpy.int was deprecated in NumPy 1.20 and was removed in NumPy 1.24. 

I swapped in `int` as you suggested and it passes 🎉 Nice catch knowing the type of `numpy.int` (or `numpy.int_`).

File: README.md [hunk 8]
```diff
@@ -42,16 +42,20 @@ We are using this on a variety of internal projects within the Conservation
...
 
-### No longer directly maintained / supported:
-On Windows, install the ones that require compiling from [Python Windows Packages](http://www.lfd.uci.edu/~gohlke/pythonlibs/).
-Then install the remainder using `pip`
+## Installation
+Trefoil is available on PyPi. To install, use:
 
+```text
+$ pip install trefoil
+```
```
Comment (nikmolnar) [inline README.md:58]: Let's move "Installation" above the "Development" section since it's the more common thing people would want to do.
